name: Scheduled Python Job

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # 指定您想要使用的 Python 版本

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行 Python 脚本
      env:
        TODAY: ${{ env.TODAY }}
      run:
        python main.py